# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'helper.ui'
#
# Created: Mon Dec 27 14:33:51 2010
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(807, 430)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.graphicsView = MyGraphicsView(self.centralwidget)
        self.graphicsView.setMinimumSize(QtCore.QSize(363, 243))
        self.graphicsView.setMaximumSize(QtCore.QSize(363, 243))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.horizontalLayout.addWidget(self.graphicsView)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 243))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        
        self.fixtureChooser = QtGui.QComboBox(self)
        self.fixtureChooser.insertItem(0,"add new")
        
        self.verticalLayout_3.addWidget(self.fixtureChooser)
        self.verticalLayout_3.addWidget(self.plainTextEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.patternLabel = QtGui.QLabel(self.centralwidget)
        self.patternLabel.setObjectName(_fromUtf8("patternLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.patternLabel)
        self.patternLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.patternLineEdit.setMinimumSize(QtCore.QSize(400, 0))
        self.patternLineEdit.setObjectName(_fromUtf8("patternLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.patternLineEdit)
        self.sortClockwiseLabel = QtGui.QLabel(self.centralwidget)
        self.sortClockwiseLabel.setObjectName(_fromUtf8("sortClockwiseLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.sortClockwiseLabel)
        self.sortClockwiseCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.sortClockwiseCheckBox.setChecked(True)
        self.sortClockwiseCheckBox.setObjectName(_fromUtf8("sortClockwiseCheckBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.sortClockwiseCheckBox)
        self.invertedYLabel = QtGui.QLabel(self.centralwidget)
        self.invertedYLabel.setObjectName(_fromUtf8("invertedYLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.invertedYLabel)
        self.invertedYCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.invertedYCheckBox.setObjectName(_fromUtf8("invertedYCheckBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.invertedYCheckBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionDelete_selected = QtGui.QAction(MainWindow)
        self.actionDelete_selected.setObjectName(_fromUtf8("actionDelete_selected"))
        self.actionMove_up = QtGui.QAction(MainWindow)
        self.actionMove_up.setObjectName(_fromUtf8("actionMove_up"))
        self.actionMove_down = QtGui.QAction(MainWindow)
        self.actionMove_down.setObjectName(_fromUtf8("actionMove_down"))
        self.actionMove_left = QtGui.QAction(MainWindow)
        self.actionMove_left.setObjectName(_fromUtf8("actionMove_left"))
        self.actionMove_right = QtGui.QAction(MainWindow)
        self.actionMove_right.setObjectName(_fromUtf8("actionMove_right"))
        self.actionZoom_In = QtGui.QAction(MainWindow)
        self.actionZoom_In.setObjectName(_fromUtf8("actionZoom_In"))
        self.actionZoom_Out = QtGui.QAction(MainWindow)
        self.actionZoom_Out.setObjectName(_fromUtf8("actionZoom_Out"))
        self.menuFile.addAction(self.actionOpen)
        self.menuEdit.addAction(self.actionDelete_selected)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionMove_up)
        self.menuEdit.addAction(self.actionMove_down)
        self.menuEdit.addAction(self.actionMove_left)
        self.menuEdit.addAction(self.actionMove_right)
        self.menuView.addAction(self.actionZoom_In)
        self.menuView.addAction(self.actionZoom_Out)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Andengine Vertex Helper", None, QtGui.QApplication.UnicodeUTF8))
        self.patternLabel.setText(QtGui.QApplication.translate("MainWindow", "Pattern", None, QtGui.QApplication.UnicodeUTF8))
        self.sortClockwiseLabel.setText(QtGui.QApplication.translate("MainWindow", "Sort Clockwise", None, QtGui.QApplication.UnicodeUTF8))
        self.invertedYLabel.setText(QtGui.QApplication.translate("MainWindow", "Inverted Y", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_selected.setText(QtGui.QApplication.translate("MainWindow", "Delete selected", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_selected.setShortcut(QtGui.QApplication.translate("MainWindow", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMove_up.setText(QtGui.QApplication.translate("MainWindow", "Move up", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMove_up.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Up", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMove_down.setText(QtGui.QApplication.translate("MainWindow", "Move down", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMove_down.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Down", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMove_left.setText(QtGui.QApplication.translate("MainWindow", "Move left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMove_left.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMove_right.setText(QtGui.QApplication.translate("MainWindow", "Move right", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMove_right.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Right", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_In.setText(QtGui.QApplication.translate("MainWindow", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_In.setShortcut(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_Out.setText(QtGui.QApplication.translate("MainWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_Out.setShortcut(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))

from graphicsview import MyGraphicsView
